### ISSUE TITLE
i don't have the install pop up

### ISSUE THREAD

**Issue by Xmoncoco** [IJustNeedOffsets/iManager#3]
i test the iManager and it don't work I got the gui but in can't use because I don't see this pop up
<img width="299" alt="Capture d’écran 2021-11-19 à 18 34 27" src="https://user-images.githubusercontent.com/87990895/142666456-f20fb9de-4b7b-4eaa-8d21-f935303fd221.png">
 (sorry for the quality)

**Comment by IJustNeedOffsets** [comment]
did you try to use an old version of iManager before? In that case just click install dependencies, wait for it to be done. quit iManager, open iManager and click install dependencies again, then click reload information when you iphone is done with respring.

**Comment by Xmoncoco** [comment]
this is my try 
https://youtu.be/LBJgHSl71i4

**Comment by IJustNeedOffsets** [comment]
So your device is connected with your computer using a cable, you installed Homebrew on your mac and installed openSSH on your jailbroken device? Btw could you tell me what ios version and what jailbreak you are using

**Comment by Xmoncoco** [comment]
this is the libhooker configurator 
![IMG_6353](https://user-images.githubusercontent.com/87990895/142685947-6b6617b8-17e3-4cfe-8360-536f5d5d0975.jpg)
and I will retry to install homebr
![IMG_D4F08D752A68-1](https://user-images.githubusercontent.com/87990895/142686183-e6dabaa1-ae25-4d5a-a04d-d54a47cdcfef.jpeg)

and I will retry to install Homebrew

**Comment by Xmoncoco** [comment]
and i do the command brew help on my new tab cmd and it work

**Comment by Xmoncoco** [comment]
if I launch the iPhone manage file in MACOS it say this
cp: /usr/local/Cellar/sshpass/*/bin/sshpass: No such file or directory
cp: /usr/local/Cellar/libusbmuxd/*/bin/iproxy: No such file or directory

**Comment by Xmoncoco** [comment]
i fond the error
on the shell script installdepend there is a problem 
i think you are not using the newest brew directory
and it works

`echo "Depend install"
echo "Starting"

sleep 0.2
cd /Applications/iphoneManage.app/Contents/Resources/tweaks ; curl -O https://cydia.akemi.ai/debs/nodelete-net.angelxwind.appsyncunified.deb
sleep 0.2
cd /Applications/iphoneManage.app/Contents/Resources/tweaks ; curl -O https://if0x.github.io/io.github.awesomebing1.sbutils_2.1.1_iphoneos-arm.deb
sleep 0.2
cd /Applications/iphoneManage.app/Contents/Resources/tweaks ; curl -O http://apt.thebigboss.org/repofiles/cydia/debs2.0/afc2kppless_1.1.5-1.deb
sleep 0.2
cd /Applications/iphoneManage.app/Contents/Resources/tweaks ; curl -O https://cydia.akemi.ai/debs/nodelete-com.linusyang.appinst.deb
echo "Downloaded Tweaks"
sleep 0.2
echo "Starting"
sleep 0.2
brew install esolitos/ipa/sshpass > /dev/null 2>&1
sleep 0.2
brew install libimobiledevice > /dev/null 2>&1
sleep 0.2
cp /opt/homebrew/Cellar/sshpass/1.06/bin/sshpass /Applications/iphoneManage.app/Contents/Resources/
cp /opt/homebrew/Cellar/libusbmuxd/2.0.2/bin/iproxy /Applications/iphoneManage.app/Contents/Resources/
echo "Installed Command Line Tools on Computer"
sleep 0.4
echo "Done. You can now start the program."
`

**Comment by Xmoncoco** [comment]
it on cp commands and some is wrong
